version: "3.5"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    container_name: "mysql-reservation"
    ports:
      - "3306:3306"
    networks:
      - reservation-network
  cassandra:
    image: cassandra:3.11
    container_name: "cassandra-reservation"
    ports:
      - "9042:9042"
    networks:
      - reservation-network
  schema-loader:
    image: ghcr.io/scalar-labs/scalardb-schema-loader:3.5.2
    container_name: "schema-loader-reservation"
    depends_on:
      - cassandra
      - mysql
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./database-docker.properties:/database.properties
      - ./schema.json:/schema.json
    entrypoint: /bin/bash
    command: /wait-for-it.sh -t 60 cassandra:9042 -- java -jar app.jar -f /schema.json --config /database.properties --replication-factor 1 --coordinator
    networks:
      - reservation-network
    restart: on-failure
networks:
  reservation-network:
    name: reservation-network
